// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_121_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mul_ln136,
        training_X_0_address0,
        training_X_0_ce0,
        training_X_0_q0,
        training_X_1_address0,
        training_X_1_ce0,
        training_X_1_q0,
        training_X_2_address0,
        training_X_2_ce0,
        training_X_2_q0,
        training_X_3_address0,
        training_X_3_ce0,
        training_X_3_q0,
        mul_ln61,
        testing_X_address0,
        testing_X_ce0,
        testing_X_q0,
        testing_X_address1,
        testing_X_ce1,
        testing_X_q1,
        mul_ln62,
        mul_ln63,
        mul_ln64,
        distance_q3_t3_out,
        distance_q3_t3_out_ap_vld,
        distance_q3_t2_out,
        distance_q3_t2_out_ap_vld,
        distance_q3_t1_out,
        distance_q3_t1_out_ap_vld,
        distance_q3_t0_out,
        distance_q3_t0_out_ap_vld,
        distance_q2_t3_out,
        distance_q2_t3_out_ap_vld,
        distance_q0_t0_out,
        distance_q0_t0_out_ap_vld,
        distance_q0_t1_out,
        distance_q0_t1_out_ap_vld,
        distance_q0_t2_out,
        distance_q0_t2_out_ap_vld,
        distance_q0_t3_out,
        distance_q0_t3_out_ap_vld,
        distance_q1_t0_out,
        distance_q1_t0_out_ap_vld,
        distance_q1_t1_out,
        distance_q1_t1_out_ap_vld,
        distance_q1_t2_out,
        distance_q1_t2_out_ap_vld,
        distance_q1_t3_out,
        distance_q1_t3_out_ap_vld,
        distance_q2_t0_out,
        distance_q2_t0_out_ap_vld,
        distance_q2_t1_out,
        distance_q2_t1_out_ap_vld,
        distance_q2_t2_out,
        distance_q2_t2_out_ap_vld,
        grp_fu_55918_p_din0,
        grp_fu_55918_p_din1,
        grp_fu_55918_p_opcode,
        grp_fu_55918_p_dout0,
        grp_fu_55918_p_ce,
        grp_fu_55922_p_din0,
        grp_fu_55922_p_din1,
        grp_fu_55922_p_opcode,
        grp_fu_55922_p_dout0,
        grp_fu_55922_p_ce,
        grp_fu_55926_p_din0,
        grp_fu_55926_p_din1,
        grp_fu_55926_p_opcode,
        grp_fu_55926_p_dout0,
        grp_fu_55926_p_ce,
        grp_fu_56117_p_din0,
        grp_fu_56117_p_dout0,
        grp_fu_56117_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] mul_ln136;
output  [15:0] training_X_0_address0;
output   training_X_0_ce0;
input  [31:0] training_X_0_q0;
output  [15:0] training_X_1_address0;
output   training_X_1_ce0;
input  [31:0] training_X_1_q0;
output  [15:0] training_X_2_address0;
output   training_X_2_ce0;
input  [31:0] training_X_2_q0;
output  [15:0] training_X_3_address0;
output   training_X_3_ce0;
input  [31:0] training_X_3_q0;
input  [15:0] mul_ln61;
output  [15:0] testing_X_address0;
output   testing_X_ce0;
input  [31:0] testing_X_q0;
output  [15:0] testing_X_address1;
output   testing_X_ce1;
input  [31:0] testing_X_q1;
input  [15:0] mul_ln62;
input  [15:0] mul_ln63;
input  [15:0] mul_ln64;
output  [63:0] distance_q3_t3_out;
output   distance_q3_t3_out_ap_vld;
output  [63:0] distance_q3_t2_out;
output   distance_q3_t2_out_ap_vld;
output  [63:0] distance_q3_t1_out;
output   distance_q3_t1_out_ap_vld;
output  [63:0] distance_q3_t0_out;
output   distance_q3_t0_out_ap_vld;
output  [63:0] distance_q2_t3_out;
output   distance_q2_t3_out_ap_vld;
output  [63:0] distance_q0_t0_out;
output   distance_q0_t0_out_ap_vld;
output  [63:0] distance_q0_t1_out;
output   distance_q0_t1_out_ap_vld;
output  [63:0] distance_q0_t2_out;
output   distance_q0_t2_out_ap_vld;
output  [63:0] distance_q0_t3_out;
output   distance_q0_t3_out_ap_vld;
output  [63:0] distance_q1_t0_out;
output   distance_q1_t0_out_ap_vld;
output  [63:0] distance_q1_t1_out;
output   distance_q1_t1_out_ap_vld;
output  [63:0] distance_q1_t2_out;
output   distance_q1_t2_out_ap_vld;
output  [63:0] distance_q1_t3_out;
output   distance_q1_t3_out_ap_vld;
output  [63:0] distance_q2_t0_out;
output   distance_q2_t0_out_ap_vld;
output  [63:0] distance_q2_t1_out;
output   distance_q2_t1_out_ap_vld;
output  [63:0] distance_q2_t2_out;
output   distance_q2_t2_out_ap_vld;
output  [31:0] grp_fu_55918_p_din0;
output  [31:0] grp_fu_55918_p_din1;
output  [1:0] grp_fu_55918_p_opcode;
input  [31:0] grp_fu_55918_p_dout0;
output   grp_fu_55918_p_ce;
output  [31:0] grp_fu_55922_p_din0;
output  [31:0] grp_fu_55922_p_din1;
output  [1:0] grp_fu_55922_p_opcode;
input  [31:0] grp_fu_55922_p_dout0;
output   grp_fu_55922_p_ce;
output  [31:0] grp_fu_55926_p_din0;
output  [31:0] grp_fu_55926_p_din1;
output  [1:0] grp_fu_55926_p_opcode;
input  [31:0] grp_fu_55926_p_dout0;
output   grp_fu_55926_p_ce;
output  [31:0] grp_fu_56117_p_din0;
input  [63:0] grp_fu_56117_p_dout0;
output   grp_fu_56117_p_ce;

reg ap_idle;
reg training_X_0_ce0;
reg training_X_1_ce0;
reg training_X_2_ce0;
reg training_X_3_ce0;
reg[15:0] testing_X_address0;
reg testing_X_ce0;
reg[15:0] testing_X_address1;
reg testing_X_ce1;
reg distance_q3_t3_out_ap_vld;
reg distance_q3_t2_out_ap_vld;
reg distance_q3_t1_out_ap_vld;
reg distance_q3_t0_out_ap_vld;
reg distance_q2_t3_out_ap_vld;
reg distance_q0_t0_out_ap_vld;
reg distance_q0_t1_out_ap_vld;
reg distance_q0_t2_out_ap_vld;
reg distance_q0_t3_out_ap_vld;
reg distance_q1_t0_out_ap_vld;
reg distance_q1_t1_out_ap_vld;
reg distance_q1_t2_out_ap_vld;
reg distance_q1_t3_out_ap_vld;
reg distance_q2_t0_out_ap_vld;
reg distance_q2_t1_out_ap_vld;
reg distance_q2_t2_out_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state8_pp0_stage3_iter1;
wire    ap_block_state12_pp0_stage3_iter2;
wire    ap_block_state16_pp0_stage3_iter3;
wire    ap_block_state20_pp0_stage3_iter4;
wire    ap_block_pp0_stage3_subdone;
reg   [0:0] icmp_ln121_reg_1039;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] reg_451;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state6_pp0_stage1_iter1;
wire    ap_block_state10_pp0_stage1_iter2;
wire    ap_block_state14_pp0_stage1_iter3;
wire    ap_block_state18_pp0_stage1_iter4;
wire    ap_block_pp0_stage1_11001;
wire    ap_block_pp0_stage3_11001;
reg   [31:0] reg_456;
reg   [31:0] reg_461;
wire   [31:0] grp_fu_403_p2;
reg   [31:0] reg_466;
reg   [31:0] reg_471;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state7_pp0_stage2_iter1;
wire    ap_block_state11_pp0_stage2_iter2;
wire    ap_block_state15_pp0_stage2_iter3;
wire    ap_block_state19_pp0_stage2_iter4;
wire    ap_block_pp0_stage2_11001;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state9_pp0_stage0_iter2;
wire    ap_block_state13_pp0_stage0_iter3;
wire    ap_block_state17_pp0_stage0_iter4;
wire    ap_block_state21_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] reg_476;
reg   [31:0] reg_481;
reg   [31:0] reg_486;
wire   [0:0] icmp_ln121_fu_579_p2;
reg   [0:0] icmp_ln121_reg_1039_pp0_iter1_reg;
reg   [0:0] icmp_ln121_reg_1039_pp0_iter2_reg;
reg   [0:0] icmp_ln121_reg_1039_pp0_iter3_reg;
wire   [15:0] zext_ln136_fu_591_p1;
reg   [15:0] zext_ln136_reg_1043;
wire   [31:0] q0_feat_fu_654_p1;
reg   [31:0] q0_feat_reg_1089;
wire   [31:0] q1_feat_fu_658_p1;
reg   [31:0] q1_feat_reg_1095;
wire   [31:0] t0_feat_fu_662_p1;
reg   [31:0] t0_feat_reg_1101;
wire   [31:0] t1_feat_fu_666_p1;
reg   [31:0] t1_feat_reg_1109;
wire   [31:0] t2_feat_fu_670_p1;
reg   [31:0] t2_feat_reg_1116;
wire   [31:0] t3_feat_fu_674_p1;
reg   [31:0] t3_feat_reg_1122;
wire   [31:0] q2_feat_fu_678_p1;
reg   [31:0] q2_feat_reg_1129;
wire   [31:0] q3_feat_fu_682_p1;
reg   [31:0] q3_feat_reg_1135;
reg   [63:0] diff_q0_t0_reg_1141;
wire   [63:0] grp_fu_410_p1;
reg   [63:0] diff_q1_t1_reg_1147;
wire   [63:0] grp_fu_413_p1;
reg   [63:0] diff_q0_t1_reg_1153;
wire   [63:0] grp_fu_416_p1;
reg   [63:0] diff_q1_t2_reg_1159;
reg   [63:0] diff_q2_t2_reg_1165;
reg   [63:0] diff_q3_t3_reg_1171;
reg   [63:0] diff_q2_t3_reg_1177;
reg   [63:0] diff_q3_t0_reg_1183;
reg   [63:0] diff_q0_t2_reg_1189;
reg   [63:0] diff_q1_t3_reg_1195;
reg   [63:0] diff_q2_t0_reg_1201;
reg   [63:0] diff_q3_t1_reg_1207;
reg   [63:0] diff_q0_t3_reg_1213;
reg   [63:0] diff_q1_t0_reg_1219;
reg   [63:0] diff_q2_t1_reg_1225;
reg   [63:0] diff_q3_t2_reg_1231;
wire   [63:0] grp_fu_435_p2;
reg   [63:0] mul_reg_1237;
wire   [63:0] grp_fu_439_p2;
reg   [63:0] mul1_reg_1242;
wire   [63:0] grp_fu_443_p2;
reg   [63:0] mul4_reg_1247;
wire   [63:0] grp_fu_447_p2;
reg   [63:0] mul5_reg_1252;
reg   [63:0] mul2_reg_1277;
reg   [63:0] mul3_reg_1282;
reg   [63:0] mul6_reg_1287;
reg   [63:0] mul7_reg_1292;
reg   [63:0] mul8_reg_1317;
reg   [63:0] mul9_reg_1322;
reg   [63:0] mul10_reg_1327;
reg   [63:0] mul11_reg_1332;
reg   [63:0] mul12_reg_1357;
reg   [63:0] mul13_reg_1362;
reg   [63:0] mul14_reg_1367;
reg   [63:0] mul15_reg_1372;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln136_1_fu_601_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln124_fu_615_p1;
wire   [63:0] zext_ln125_fu_626_p1;
wire   [63:0] zext_ln126_fu_640_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln127_fu_649_p1;
reg   [63:0] distance_q2_t2_fu_88;
wire   [63:0] grp_fu_419_p2;
reg   [63:0] ap_sig_allocacmp_distance_q2_t2_load;
wire    ap_block_pp0_stage2;
wire    ap_loop_init;
reg   [63:0] distance_q2_t1_fu_92;
wire   [63:0] grp_fu_427_p2;
reg   [63:0] ap_sig_allocacmp_distance_q2_t1_load;
reg   [63:0] distance_q2_t0_fu_96;
reg   [63:0] ap_sig_allocacmp_distance_q2_t0_load;
wire    ap_block_pp0_stage3;
reg   [63:0] distance_q1_t3_fu_100;
wire   [63:0] grp_fu_423_p2;
reg   [63:0] ap_sig_allocacmp_distance_q1_t3_load;
reg   [63:0] distance_q1_t2_fu_104;
wire   [63:0] grp_fu_431_p2;
reg   [63:0] ap_sig_allocacmp_distance_q1_t2_load;
reg   [63:0] distance_q1_t1_fu_108;
reg   [63:0] ap_sig_allocacmp_distance_q1_t1_load;
reg   [63:0] distance_q1_t0_fu_112;
reg   [63:0] ap_sig_allocacmp_distance_q1_t0_load;
reg   [63:0] distance_q0_t3_fu_116;
reg   [63:0] ap_sig_allocacmp_distance_q0_t3_load;
reg   [63:0] distance_q0_t2_fu_120;
reg   [63:0] ap_sig_allocacmp_distance_q0_t2_load;
reg   [63:0] distance_q0_t1_fu_124;
reg   [63:0] ap_sig_allocacmp_distance_q0_t1_load;
reg   [63:0] distance_q0_t0_fu_128;
reg   [63:0] ap_sig_allocacmp_distance_q0_t0_load;
reg   [63:0] distance_q2_t3_fu_132;
reg   [63:0] ap_sig_allocacmp_distance_q2_t3_load;
reg   [63:0] distance_q3_t0_fu_136;
reg   [63:0] ap_sig_allocacmp_distance_q3_t0_load;
reg   [63:0] distance_q3_t1_fu_140;
reg   [63:0] ap_sig_allocacmp_distance_q3_t1_load;
reg   [63:0] distance_q3_t2_fu_144;
reg   [63:0] ap_sig_allocacmp_distance_q3_t2_load;
reg   [63:0] distance_q3_t3_fu_148;
reg   [63:0] ap_sig_allocacmp_distance_q3_t3_load;
reg   [5:0] j_fu_152;
wire   [5:0] add_ln121_fu_585_p2;
reg   [5:0] ap_sig_allocacmp_j_1;
wire    ap_block_pp0_stage0_01001;
reg   [31:0] grp_fu_391_p0;
reg   [31:0] grp_fu_391_p1;
reg   [31:0] grp_fu_395_p0;
reg   [31:0] grp_fu_395_p1;
reg   [31:0] grp_fu_399_p0;
reg   [31:0] grp_fu_399_p1;
reg   [31:0] grp_fu_403_p0;
reg   [31:0] grp_fu_403_p1;
reg   [31:0] grp_fu_407_p0;
reg   [31:0] grp_fu_410_p0;
reg   [31:0] grp_fu_413_p0;
reg   [31:0] grp_fu_416_p0;
reg   [63:0] grp_fu_419_p0;
reg   [63:0] grp_fu_419_p1;
reg   [63:0] grp_fu_423_p0;
reg   [63:0] grp_fu_423_p1;
reg   [63:0] grp_fu_427_p0;
reg   [63:0] grp_fu_427_p1;
reg   [63:0] grp_fu_431_p0;
reg   [63:0] grp_fu_431_p1;
reg   [63:0] grp_fu_435_p0;
reg   [63:0] grp_fu_435_p1;
reg   [63:0] grp_fu_439_p0;
reg   [63:0] grp_fu_439_p1;
reg   [63:0] grp_fu_443_p0;
reg   [63:0] grp_fu_443_p1;
reg   [63:0] grp_fu_447_p0;
reg   [63:0] grp_fu_447_p1;
wire   [15:0] add_ln136_fu_595_p2;
wire   [15:0] add_ln124_fu_609_p2;
wire   [15:0] add_ln125_fu_620_p2;
wire   [15:0] add_ln126_fu_636_p2;
wire   [15:0] add_ln127_fu_645_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter4_stage0;
reg    ap_idle_pp0_0to3;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_1to5;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_block_pp0_stage2_00001;
wire    ap_block_pp0_stage3_00001;
wire    ap_block_pp0_stage0_00001;
wire    ap_block_pp0_stage1_00001;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

kNN_PredictAll_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_4_full_dsp_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_403_p0),
    .din1(grp_fu_403_p1),
    .ce(1'b1),
    .dout(grp_fu_403_p2)
);

kNN_PredictAll_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_410_p0),
    .ce(1'b1),
    .dout(grp_fu_410_p1)
);

kNN_PredictAll_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_413_p0),
    .ce(1'b1),
    .dout(grp_fu_413_p1)
);

kNN_PredictAll_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_416_p0),
    .ce(1'b1),
    .dout(grp_fu_416_p1)
);

kNN_PredictAll_dadd_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_5_full_dsp_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_419_p0),
    .din1(grp_fu_419_p1),
    .ce(1'b1),
    .dout(grp_fu_419_p2)
);

kNN_PredictAll_dadd_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_5_full_dsp_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_423_p0),
    .din1(grp_fu_423_p1),
    .ce(1'b1),
    .dout(grp_fu_423_p2)
);

kNN_PredictAll_dadd_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_5_full_dsp_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_427_p0),
    .din1(grp_fu_427_p1),
    .ce(1'b1),
    .dout(grp_fu_427_p2)
);

kNN_PredictAll_dadd_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_5_full_dsp_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_431_p0),
    .din1(grp_fu_431_p1),
    .ce(1'b1),
    .dout(grp_fu_431_p2)
);

kNN_PredictAll_dmul_64ns_64ns_64_5_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_5_max_dsp_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_435_p0),
    .din1(grp_fu_435_p1),
    .ce(1'b1),
    .dout(grp_fu_435_p2)
);

kNN_PredictAll_dmul_64ns_64ns_64_5_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_5_max_dsp_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_439_p0),
    .din1(grp_fu_439_p1),
    .ce(1'b1),
    .dout(grp_fu_439_p2)
);

kNN_PredictAll_dmul_64ns_64ns_64_5_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_5_max_dsp_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_443_p0),
    .din1(grp_fu_443_p1),
    .ce(1'b1),
    .dout(grp_fu_443_p2)
);

kNN_PredictAll_dmul_64ns_64ns_64_5_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_5_max_dsp_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_447_p0),
    .din1(grp_fu_447_p1),
    .ce(1'b1),
    .dout(grp_fu_447_p2)
);

kNN_PredictAll_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q0_t0_fu_128 <= 64'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        distance_q0_t0_fu_128 <= grp_fu_419_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q0_t1_fu_124 <= 64'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        distance_q0_t1_fu_124 <= grp_fu_427_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q0_t2_fu_120 <= 64'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        distance_q0_t2_fu_120 <= grp_fu_419_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            distance_q0_t3_fu_116 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            distance_q0_t3_fu_116 <= grp_fu_419_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            distance_q1_t0_fu_112 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            distance_q1_t0_fu_112 <= grp_fu_423_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q1_t1_fu_108 <= 64'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        distance_q1_t1_fu_108 <= grp_fu_423_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q1_t2_fu_104 <= 64'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        distance_q1_t2_fu_104 <= grp_fu_431_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q1_t3_fu_100 <= 64'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        distance_q1_t3_fu_100 <= grp_fu_423_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q2_t0_fu_96 <= 64'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        distance_q2_t0_fu_96 <= grp_fu_427_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            distance_q2_t1_fu_92 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            distance_q2_t1_fu_92 <= grp_fu_427_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q2_t2_fu_88 <= 64'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        distance_q2_t2_fu_88 <= grp_fu_419_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q2_t3_fu_132 <= 64'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        distance_q2_t3_fu_132 <= grp_fu_427_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q3_t0_fu_136 <= 64'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        distance_q3_t0_fu_136 <= grp_fu_431_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q3_t1_fu_140 <= 64'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        distance_q3_t1_fu_140 <= grp_fu_431_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            distance_q3_t2_fu_144 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            distance_q3_t2_fu_144 <= grp_fu_431_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q3_t3_fu_148 <= 64'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        distance_q3_t3_fu_148 <= grp_fu_423_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln121_fu_579_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_152 <= add_ln121_fu_585_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_152 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        diff_q0_t0_reg_1141 <= grp_fu_56117_p_dout0;
        diff_q0_t1_reg_1153 <= grp_fu_413_p1;
        diff_q1_t1_reg_1147 <= grp_fu_410_p1;
        diff_q1_t2_reg_1159 <= grp_fu_416_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        diff_q0_t2_reg_1189 <= grp_fu_56117_p_dout0;
        diff_q1_t3_reg_1195 <= grp_fu_410_p1;
        diff_q2_t0_reg_1201 <= grp_fu_413_p1;
        diff_q3_t1_reg_1207 <= grp_fu_416_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        diff_q0_t3_reg_1213 <= grp_fu_56117_p_dout0;
        diff_q1_t0_reg_1219 <= grp_fu_410_p1;
        diff_q2_t1_reg_1225 <= grp_fu_413_p1;
        diff_q3_t2_reg_1231 <= grp_fu_416_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        diff_q2_t2_reg_1165 <= grp_fu_56117_p_dout0;
        diff_q2_t3_reg_1177 <= grp_fu_413_p1;
        diff_q3_t0_reg_1183 <= grp_fu_416_p1;
        diff_q3_t3_reg_1171 <= grp_fu_410_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln121_reg_1039 <= icmp_ln121_fu_579_p2;
        icmp_ln121_reg_1039_pp0_iter1_reg <= icmp_ln121_reg_1039;
        icmp_ln121_reg_1039_pp0_iter2_reg <= icmp_ln121_reg_1039_pp0_iter1_reg;
        icmp_ln121_reg_1039_pp0_iter3_reg <= icmp_ln121_reg_1039_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul10_reg_1327 <= grp_fu_443_p2;
        mul11_reg_1332 <= grp_fu_447_p2;
        mul8_reg_1317 <= grp_fu_435_p2;
        mul9_reg_1322 <= grp_fu_439_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul12_reg_1357 <= grp_fu_435_p2;
        mul13_reg_1362 <= grp_fu_439_p2;
        mul14_reg_1367 <= grp_fu_443_p2;
        mul15_reg_1372 <= grp_fu_447_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul1_reg_1242 <= grp_fu_439_p2;
        mul4_reg_1247 <= grp_fu_443_p2;
        mul5_reg_1252 <= grp_fu_447_p2;
        mul_reg_1237 <= grp_fu_435_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul2_reg_1277 <= grp_fu_435_p2;
        mul3_reg_1282 <= grp_fu_439_p2;
        mul6_reg_1287 <= grp_fu_443_p2;
        mul7_reg_1292 <= grp_fu_447_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln121_reg_1039 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        q0_feat_reg_1089 <= q0_feat_fu_654_p1;
        q1_feat_reg_1095 <= q1_feat_fu_658_p1;
        t0_feat_reg_1101 <= t0_feat_fu_662_p1;
        t1_feat_reg_1109 <= t1_feat_fu_666_p1;
        t2_feat_reg_1116 <= t2_feat_fu_670_p1;
        t3_feat_reg_1122 <= t3_feat_fu_674_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln121_reg_1039 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        q2_feat_reg_1129 <= q2_feat_fu_678_p1;
        q3_feat_reg_1135 <= q3_feat_fu_682_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_451 <= grp_fu_55918_p_dout0;
        reg_456 <= grp_fu_55922_p_dout0;
        reg_461 <= grp_fu_55926_p_dout0;
        reg_466 <= grp_fu_403_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_471 <= grp_fu_55918_p_dout0;
        reg_476 <= grp_fu_55922_p_dout0;
        reg_481 <= grp_fu_55926_p_dout0;
        reg_486 <= grp_fu_403_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_fu_579_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln136_reg_1043[5 : 0] <= zext_ln136_fu_591_p1[5 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln121_reg_1039 == 1'd1) & (1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln121_reg_1039_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter4_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter4_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to5 = 1'b1;
    end else begin
        ap_idle_pp0_1to5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_distance_q0_t0_load = grp_fu_419_p2;
    end else begin
        ap_sig_allocacmp_distance_q0_t0_load = distance_q0_t0_fu_128;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_distance_q0_t1_load = grp_fu_427_p2;
    end else begin
        ap_sig_allocacmp_distance_q0_t1_load = distance_q0_t1_fu_124;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_distance_q0_t2_load = grp_fu_419_p2;
    end else begin
        ap_sig_allocacmp_distance_q0_t2_load = distance_q0_t2_fu_120;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_distance_q0_t3_load = grp_fu_419_p2;
    end else begin
        ap_sig_allocacmp_distance_q0_t3_load = distance_q0_t3_fu_116;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_distance_q1_t0_load = grp_fu_423_p2;
    end else begin
        ap_sig_allocacmp_distance_q1_t0_load = distance_q1_t0_fu_112;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_distance_q1_t1_load = grp_fu_423_p2;
    end else begin
        ap_sig_allocacmp_distance_q1_t1_load = distance_q1_t1_fu_108;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_distance_q1_t2_load = grp_fu_431_p2;
    end else begin
        ap_sig_allocacmp_distance_q1_t2_load = distance_q1_t2_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_distance_q1_t3_load = grp_fu_423_p2;
    end else begin
        ap_sig_allocacmp_distance_q1_t3_load = distance_q1_t3_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_distance_q2_t0_load = grp_fu_427_p2;
    end else begin
        ap_sig_allocacmp_distance_q2_t0_load = distance_q2_t0_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_distance_q2_t1_load = grp_fu_427_p2;
    end else begin
        ap_sig_allocacmp_distance_q2_t1_load = distance_q2_t1_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_distance_q2_t2_load = grp_fu_419_p2;
    end else begin
        ap_sig_allocacmp_distance_q2_t2_load = distance_q2_t2_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_distance_q2_t3_load = grp_fu_427_p2;
    end else begin
        ap_sig_allocacmp_distance_q2_t3_load = distance_q2_t3_fu_132;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_distance_q3_t0_load = grp_fu_431_p2;
    end else begin
        ap_sig_allocacmp_distance_q3_t0_load = distance_q3_t0_fu_136;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_distance_q3_t1_load = grp_fu_431_p2;
    end else begin
        ap_sig_allocacmp_distance_q3_t1_load = distance_q3_t1_fu_140;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_distance_q3_t2_load = grp_fu_431_p2;
    end else begin
        ap_sig_allocacmp_distance_q3_t2_load = distance_q3_t2_fu_144;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_distance_q3_t3_load = grp_fu_423_p2;
    end else begin
        ap_sig_allocacmp_distance_q3_t3_load = distance_q3_t3_fu_148;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_152;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_1039_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q0_t0_out_ap_vld = 1'b1;
    end else begin
        distance_q0_t0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_1039_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q0_t1_out_ap_vld = 1'b1;
    end else begin
        distance_q0_t1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_1039_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q0_t2_out_ap_vld = 1'b1;
    end else begin
        distance_q0_t2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_1039_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q0_t3_out_ap_vld = 1'b1;
    end else begin
        distance_q0_t3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_1039_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q1_t0_out_ap_vld = 1'b1;
    end else begin
        distance_q1_t0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_1039_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q1_t1_out_ap_vld = 1'b1;
    end else begin
        distance_q1_t1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_1039_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q1_t2_out_ap_vld = 1'b1;
    end else begin
        distance_q1_t2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_1039_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q1_t3_out_ap_vld = 1'b1;
    end else begin
        distance_q1_t3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_1039_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q2_t0_out_ap_vld = 1'b1;
    end else begin
        distance_q2_t0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_1039_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q2_t1_out_ap_vld = 1'b1;
    end else begin
        distance_q2_t1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_1039_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q2_t2_out_ap_vld = 1'b1;
    end else begin
        distance_q2_t2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_1039_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q2_t3_out_ap_vld = 1'b1;
    end else begin
        distance_q2_t3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_1039_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q3_t0_out_ap_vld = 1'b1;
    end else begin
        distance_q3_t0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_1039_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q3_t1_out_ap_vld = 1'b1;
    end else begin
        distance_q3_t1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_1039_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q3_t2_out_ap_vld = 1'b1;
    end else begin
        distance_q3_t2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_1039_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_q3_t3_out_ap_vld = 1'b1;
    end else begin
        distance_q3_t3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_391_p0 = q2_feat_reg_1129;
    end else if ((((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_391_p0 = q0_feat_reg_1089;
    end else begin
        grp_fu_391_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_391_p1 = t3_feat_reg_1122;
    end else if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_391_p1 = t2_feat_reg_1116;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_391_p1 = t0_feat_reg_1101;
    end else begin
        grp_fu_391_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_395_p0 = q3_feat_reg_1135;
    end else if ((((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_395_p0 = q1_feat_reg_1095;
    end else begin
        grp_fu_395_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_395_p1 = t0_feat_reg_1101;
    end else if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_395_p1 = t3_feat_reg_1122;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_395_p1 = t1_feat_reg_1109;
    end else begin
        grp_fu_395_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_399_p0 = q2_feat_reg_1129;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_399_p0 = q0_feat_reg_1089;
    end else begin
        grp_fu_399_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_399_p1 = t0_feat_reg_1101;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_399_p1 = t3_feat_reg_1122;
    end else if ((((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_399_p1 = t1_feat_reg_1109;
    end else begin
        grp_fu_399_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_403_p0 = q3_feat_reg_1135;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_403_p0 = q1_feat_reg_1095;
    end else begin
        grp_fu_403_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_403_p1 = t1_feat_reg_1109;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_403_p1 = t0_feat_reg_1101;
    end else if ((((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_403_p1 = t2_feat_reg_1116;
    end else begin
        grp_fu_403_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_407_p0 = reg_471;
    end else if ((((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_407_p0 = reg_451;
    end else begin
        grp_fu_407_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_410_p0 = reg_476;
    end else if ((((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_410_p0 = reg_456;
    end else begin
        grp_fu_410_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_413_p0 = reg_481;
    end else if ((((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_413_p0 = reg_461;
    end else begin
        grp_fu_413_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_416_p0 = reg_486;
    end else if ((((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_416_p0 = reg_466;
    end else begin
        grp_fu_416_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_419_p0 = ap_sig_allocacmp_distance_q0_t3_load;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_419_p0 = ap_sig_allocacmp_distance_q0_t2_load;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_419_p0 = ap_sig_allocacmp_distance_q2_t2_load;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_419_p0 = ap_sig_allocacmp_distance_q0_t0_load;
    end else begin
        grp_fu_419_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_419_p1 = mul12_reg_1357;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_419_p1 = mul8_reg_1317;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_419_p1 = mul2_reg_1277;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_419_p1 = mul_reg_1237;
    end else begin
        grp_fu_419_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_423_p0 = ap_sig_allocacmp_distance_q1_t0_load;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_423_p0 = ap_sig_allocacmp_distance_q1_t3_load;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_423_p0 = ap_sig_allocacmp_distance_q3_t3_load;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_423_p0 = ap_sig_allocacmp_distance_q1_t1_load;
    end else begin
        grp_fu_423_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_423_p1 = mul13_reg_1362;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_423_p1 = mul9_reg_1322;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_423_p1 = mul3_reg_1282;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_423_p1 = mul1_reg_1242;
    end else begin
        grp_fu_423_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_427_p0 = ap_sig_allocacmp_distance_q2_t1_load;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_427_p0 = ap_sig_allocacmp_distance_q2_t0_load;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_427_p0 = ap_sig_allocacmp_distance_q2_t3_load;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_427_p0 = ap_sig_allocacmp_distance_q0_t1_load;
    end else begin
        grp_fu_427_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_427_p1 = mul14_reg_1367;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_427_p1 = mul10_reg_1327;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_427_p1 = mul6_reg_1287;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_427_p1 = mul4_reg_1247;
    end else begin
        grp_fu_427_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_431_p0 = ap_sig_allocacmp_distance_q3_t2_load;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_431_p0 = ap_sig_allocacmp_distance_q3_t1_load;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_431_p0 = ap_sig_allocacmp_distance_q3_t0_load;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_431_p0 = ap_sig_allocacmp_distance_q1_t2_load;
    end else begin
        grp_fu_431_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_431_p1 = mul15_reg_1372;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_431_p1 = mul11_reg_1332;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_431_p1 = mul7_reg_1292;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_431_p1 = mul5_reg_1252;
    end else begin
        grp_fu_431_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_435_p0 = diff_q0_t3_reg_1213;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_435_p0 = diff_q0_t2_reg_1189;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_435_p0 = diff_q2_t2_reg_1165;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_435_p0 = diff_q0_t0_reg_1141;
        end else begin
            grp_fu_435_p0 = 'bx;
        end
    end else begin
        grp_fu_435_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_435_p1 = diff_q0_t3_reg_1213;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_435_p1 = diff_q0_t2_reg_1189;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_435_p1 = diff_q2_t2_reg_1165;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_435_p1 = diff_q0_t0_reg_1141;
        end else begin
            grp_fu_435_p1 = 'bx;
        end
    end else begin
        grp_fu_435_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_439_p0 = diff_q1_t0_reg_1219;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_439_p0 = diff_q1_t3_reg_1195;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_439_p0 = diff_q3_t3_reg_1171;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_439_p0 = diff_q1_t1_reg_1147;
        end else begin
            grp_fu_439_p0 = 'bx;
        end
    end else begin
        grp_fu_439_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_439_p1 = diff_q1_t0_reg_1219;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_439_p1 = diff_q1_t3_reg_1195;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_439_p1 = diff_q3_t3_reg_1171;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_439_p1 = diff_q1_t1_reg_1147;
        end else begin
            grp_fu_439_p1 = 'bx;
        end
    end else begin
        grp_fu_439_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_443_p0 = diff_q2_t1_reg_1225;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_443_p0 = diff_q2_t0_reg_1201;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_443_p0 = diff_q2_t3_reg_1177;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_443_p0 = diff_q0_t1_reg_1153;
        end else begin
            grp_fu_443_p0 = 'bx;
        end
    end else begin
        grp_fu_443_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_443_p1 = diff_q2_t1_reg_1225;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_443_p1 = diff_q2_t0_reg_1201;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_443_p1 = diff_q2_t3_reg_1177;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_443_p1 = diff_q0_t1_reg_1153;
        end else begin
            grp_fu_443_p1 = 'bx;
        end
    end else begin
        grp_fu_443_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_447_p0 = diff_q3_t2_reg_1231;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_447_p0 = diff_q3_t1_reg_1207;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_447_p0 = diff_q3_t0_reg_1183;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_447_p0 = diff_q1_t2_reg_1159;
        end else begin
            grp_fu_447_p0 = 'bx;
        end
    end else begin
        grp_fu_447_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_447_p1 = diff_q3_t2_reg_1231;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_447_p1 = diff_q3_t1_reg_1207;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_447_p1 = diff_q3_t0_reg_1183;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_447_p1 = diff_q1_t2_reg_1159;
        end else begin
            grp_fu_447_p1 = 'bx;
        end
    end else begin
        grp_fu_447_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            testing_X_address0 = zext_ln127_fu_649_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            testing_X_address0 = zext_ln125_fu_626_p1;
        end else begin
            testing_X_address0 = 'bx;
        end
    end else begin
        testing_X_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            testing_X_address1 = zext_ln126_fu_640_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            testing_X_address1 = zext_ln124_fu_615_p1;
        end else begin
            testing_X_address1 = 'bx;
        end
    end else begin
        testing_X_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        testing_X_ce0 = 1'b1;
    end else begin
        testing_X_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        testing_X_ce1 = 1'b1;
    end else begin
        testing_X_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        training_X_0_ce0 = 1'b1;
    end else begin
        training_X_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        training_X_1_ce0 = 1'b1;
    end else begin
        training_X_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        training_X_2_ce0 = 1'b1;
    end else begin
        training_X_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        training_X_3_ce0 = 1'b1;
    end else begin
        training_X_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to5 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln121_fu_585_p2 = (ap_sig_allocacmp_j_1 + 6'd1);

assign add_ln124_fu_609_p2 = (mul_ln61 + zext_ln136_fu_591_p1);

assign add_ln125_fu_620_p2 = (mul_ln62 + zext_ln136_fu_591_p1);

assign add_ln126_fu_636_p2 = (mul_ln63 + zext_ln136_reg_1043);

assign add_ln127_fu_645_p2 = (mul_ln64 + zext_ln136_reg_1043);

assign add_ln136_fu_595_p2 = (mul_ln136 + zext_ln136_fu_591_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage3_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign distance_q0_t0_out = distance_q0_t0_fu_128;

assign distance_q0_t1_out = distance_q0_t1_fu_124;

assign distance_q0_t2_out = distance_q0_t2_fu_120;

assign distance_q0_t3_out = distance_q0_t3_fu_116;

assign distance_q1_t0_out = distance_q1_t0_fu_112;

assign distance_q1_t1_out = distance_q1_t1_fu_108;

assign distance_q1_t2_out = distance_q1_t2_fu_104;

assign distance_q1_t3_out = distance_q1_t3_fu_100;

assign distance_q2_t0_out = distance_q2_t0_fu_96;

assign distance_q2_t1_out = distance_q2_t1_fu_92;

assign distance_q2_t2_out = distance_q2_t2_fu_88;

assign distance_q2_t3_out = distance_q2_t3_fu_132;

assign distance_q3_t0_out = distance_q3_t0_fu_136;

assign distance_q3_t1_out = distance_q3_t1_fu_140;

assign distance_q3_t2_out = distance_q3_t2_fu_144;

assign distance_q3_t3_out = distance_q3_t3_fu_148;

assign grp_fu_55918_p_ce = 1'b1;

assign grp_fu_55918_p_din0 = grp_fu_391_p0;

assign grp_fu_55918_p_din1 = grp_fu_391_p1;

assign grp_fu_55918_p_opcode = 2'd1;

assign grp_fu_55922_p_ce = 1'b1;

assign grp_fu_55922_p_din0 = grp_fu_395_p0;

assign grp_fu_55922_p_din1 = grp_fu_395_p1;

assign grp_fu_55922_p_opcode = 2'd1;

assign grp_fu_55926_p_ce = 1'b1;

assign grp_fu_55926_p_din0 = grp_fu_399_p0;

assign grp_fu_55926_p_din1 = grp_fu_399_p1;

assign grp_fu_55926_p_opcode = 2'd1;

assign grp_fu_56117_p_ce = 1'b1;

assign grp_fu_56117_p_din0 = grp_fu_407_p0;

assign icmp_ln121_fu_579_p2 = ((ap_sig_allocacmp_j_1 == 6'd43) ? 1'b1 : 1'b0);

assign q0_feat_fu_654_p1 = testing_X_q1;

assign q1_feat_fu_658_p1 = testing_X_q0;

assign q2_feat_fu_678_p1 = testing_X_q1;

assign q3_feat_fu_682_p1 = testing_X_q0;

assign t0_feat_fu_662_p1 = training_X_0_q0;

assign t1_feat_fu_666_p1 = training_X_1_q0;

assign t2_feat_fu_670_p1 = training_X_2_q0;

assign t3_feat_fu_674_p1 = training_X_3_q0;

assign training_X_0_address0 = zext_ln136_1_fu_601_p1;

assign training_X_1_address0 = zext_ln136_1_fu_601_p1;

assign training_X_2_address0 = zext_ln136_1_fu_601_p1;

assign training_X_3_address0 = zext_ln136_1_fu_601_p1;

assign zext_ln124_fu_615_p1 = add_ln124_fu_609_p2;

assign zext_ln125_fu_626_p1 = add_ln125_fu_620_p2;

assign zext_ln126_fu_640_p1 = add_ln126_fu_636_p2;

assign zext_ln127_fu_649_p1 = add_ln127_fu_645_p2;

assign zext_ln136_1_fu_601_p1 = add_ln136_fu_595_p2;

assign zext_ln136_fu_591_p1 = ap_sig_allocacmp_j_1;

always @ (posedge ap_clk) begin
    zext_ln136_reg_1043[15:6] <= 10'b0000000000;
end

endmodule //kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_121_4
