// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_236_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        histogram_q0_address0,
        histogram_q0_ce0,
        histogram_q0_q0,
        histogram_q1_address0,
        histogram_q1_ce0,
        histogram_q1_q0,
        histogram_q2_address0,
        histogram_q2_ce0,
        histogram_q2_q0,
        histogram_q3_address0,
        histogram_q3_ce0,
        histogram_q3_q0,
        mostPopular_q3_out,
        mostPopular_q3_out_ap_vld,
        mostPopular_q2_out,
        mostPopular_q2_out_ap_vld,
        mostPopular_q1_out,
        mostPopular_q1_out_ap_vld,
        mostPopular_q0_out,
        mostPopular_q0_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] histogram_q0_address0;
output   histogram_q0_ce0;
input  [7:0] histogram_q0_q0;
output  [2:0] histogram_q1_address0;
output   histogram_q1_ce0;
input  [7:0] histogram_q1_q0;
output  [2:0] histogram_q2_address0;
output   histogram_q2_ce0;
input  [7:0] histogram_q2_q0;
output  [2:0] histogram_q3_address0;
output   histogram_q3_ce0;
input  [7:0] histogram_q3_q0;
output  [7:0] mostPopular_q3_out;
output   mostPopular_q3_out_ap_vld;
output  [7:0] mostPopular_q2_out;
output   mostPopular_q2_out_ap_vld;
output  [7:0] mostPopular_q1_out;
output   mostPopular_q1_out_ap_vld;
output  [7:0] mostPopular_q0_out;
output   mostPopular_q0_out_ap_vld;

reg ap_idle;
reg histogram_q0_ce0;
reg histogram_q1_ce0;
reg histogram_q2_ce0;
reg histogram_q3_ce0;
reg mostPopular_q3_out_ap_vld;
reg mostPopular_q2_out_ap_vld;
reg mostPopular_q1_out_ap_vld;
reg mostPopular_q0_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln236_fu_210_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [2:0] i_1_reg_489;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln236_fu_222_p1;
wire    ap_block_pp0_stage0;
reg   [7:0] mostPopular_q0_fu_46;
wire   [7:0] mostPopular_q0_1_fu_272_p3;
wire    ap_loop_init;
reg   [7:0] mostPopular_q1_fu_50;
wire   [7:0] mostPopular_q1_2_fu_298_p3;
reg   [7:0] mostPopular_q2_fu_54;
wire   [7:0] mostPopular_q2_1_fu_324_p3;
reg   [7:0] mostPopular_q3_fu_58;
wire   [7:0] mostPopular_q3_4_fu_350_p3;
reg   [31:0] mostPopularCount_q0_fu_62;
wire   [31:0] mostPopularCount_q0_1_fu_280_p3;
reg   [31:0] mostPopularCount_q1_fu_66;
wire   [31:0] mostPopularCount_q1_2_fu_306_p3;
reg   [31:0] mostPopularCount_q2_fu_70;
wire   [31:0] mostPopularCount_q2_1_fu_332_p3;
reg   [31:0] mostPopularCount_q3_fu_74;
wire   [31:0] mostPopularCount_q3_2_fu_358_p3;
reg   [2:0] mostPopular_q3_1_fu_78;
wire   [2:0] i_fu_216_p2;
reg   [2:0] ap_sig_allocacmp_i_1;
wire    ap_block_pp0_stage0_01001;
wire  signed [31:0] sext_ln239_fu_259_p1;
wire   [0:0] icmp_ln239_fu_263_p2;
wire   [7:0] zext_ln242_fu_269_p1;
wire  signed [31:0] sext_ln244_fu_288_p1;
wire   [0:0] icmp_ln244_fu_292_p2;
wire  signed [31:0] sext_ln249_fu_314_p1;
wire   [0:0] icmp_ln249_fu_318_p2;
wire  signed [31:0] sext_ln254_fu_340_p1;
wire   [0:0] icmp_ln254_fu_344_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

kNN_PredictAll_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            mostPopularCount_q0_fu_62 <= 32'd4294967295;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            mostPopularCount_q0_fu_62 <= mostPopularCount_q0_1_fu_280_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            mostPopularCount_q1_fu_66 <= 32'd4294967295;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            mostPopularCount_q1_fu_66 <= mostPopularCount_q1_2_fu_306_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            mostPopularCount_q2_fu_70 <= 32'd4294967295;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            mostPopularCount_q2_fu_70 <= mostPopularCount_q2_1_fu_332_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            mostPopularCount_q3_fu_74 <= 32'd4294967295;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            mostPopularCount_q3_fu_74 <= mostPopularCount_q3_2_fu_358_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            mostPopular_q0_fu_46 <= 8'd255;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            mostPopular_q0_fu_46 <= mostPopular_q0_1_fu_272_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            mostPopular_q1_fu_50 <= 8'd255;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            mostPopular_q1_fu_50 <= mostPopular_q1_2_fu_298_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            mostPopular_q2_fu_54 <= 8'd255;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            mostPopular_q2_fu_54 <= mostPopular_q2_1_fu_324_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln236_fu_210_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            mostPopular_q3_1_fu_78 <= i_fu_216_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            mostPopular_q3_1_fu_78 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            mostPopular_q3_fu_58 <= 8'd255;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            mostPopular_q3_fu_58 <= mostPopular_q3_4_fu_350_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_1_reg_489 <= ap_sig_allocacmp_i_1;
    end
end

always @ (*) begin
    if (((icmp_ln236_fu_210_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_1 = mostPopular_q3_1_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        histogram_q0_ce0 = 1'b1;
    end else begin
        histogram_q0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        histogram_q1_ce0 = 1'b1;
    end else begin
        histogram_q1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        histogram_q2_ce0 = 1'b1;
    end else begin
        histogram_q2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        histogram_q3_ce0 = 1'b1;
    end else begin
        histogram_q3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln236_fu_210_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mostPopular_q0_out_ap_vld = 1'b1;
    end else begin
        mostPopular_q0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln236_fu_210_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mostPopular_q1_out_ap_vld = 1'b1;
    end else begin
        mostPopular_q1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln236_fu_210_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mostPopular_q2_out_ap_vld = 1'b1;
    end else begin
        mostPopular_q2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln236_fu_210_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mostPopular_q3_out_ap_vld = 1'b1;
    end else begin
        mostPopular_q3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign histogram_q0_address0 = zext_ln236_fu_222_p1;

assign histogram_q1_address0 = zext_ln236_fu_222_p1;

assign histogram_q2_address0 = zext_ln236_fu_222_p1;

assign histogram_q3_address0 = zext_ln236_fu_222_p1;

assign i_fu_216_p2 = (ap_sig_allocacmp_i_1 + 3'd1);

assign icmp_ln236_fu_210_p2 = ((ap_sig_allocacmp_i_1 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln239_fu_263_p2 = (($signed(mostPopularCount_q0_fu_62) < $signed(sext_ln239_fu_259_p1)) ? 1'b1 : 1'b0);

assign icmp_ln244_fu_292_p2 = (($signed(mostPopularCount_q1_fu_66) < $signed(sext_ln244_fu_288_p1)) ? 1'b1 : 1'b0);

assign icmp_ln249_fu_318_p2 = (($signed(mostPopularCount_q2_fu_70) < $signed(sext_ln249_fu_314_p1)) ? 1'b1 : 1'b0);

assign icmp_ln254_fu_344_p2 = (($signed(mostPopularCount_q3_fu_74) < $signed(sext_ln254_fu_340_p1)) ? 1'b1 : 1'b0);

assign mostPopularCount_q0_1_fu_280_p3 = ((icmp_ln239_fu_263_p2[0:0] == 1'b1) ? sext_ln239_fu_259_p1 : mostPopularCount_q0_fu_62);

assign mostPopularCount_q1_2_fu_306_p3 = ((icmp_ln244_fu_292_p2[0:0] == 1'b1) ? sext_ln244_fu_288_p1 : mostPopularCount_q1_fu_66);

assign mostPopularCount_q2_1_fu_332_p3 = ((icmp_ln249_fu_318_p2[0:0] == 1'b1) ? sext_ln249_fu_314_p1 : mostPopularCount_q2_fu_70);

assign mostPopularCount_q3_2_fu_358_p3 = ((icmp_ln254_fu_344_p2[0:0] == 1'b1) ? sext_ln254_fu_340_p1 : mostPopularCount_q3_fu_74);

assign mostPopular_q0_1_fu_272_p3 = ((icmp_ln239_fu_263_p2[0:0] == 1'b1) ? zext_ln242_fu_269_p1 : mostPopular_q0_fu_46);

assign mostPopular_q0_out = mostPopular_q0_fu_46;

assign mostPopular_q1_2_fu_298_p3 = ((icmp_ln244_fu_292_p2[0:0] == 1'b1) ? zext_ln242_fu_269_p1 : mostPopular_q1_fu_50);

assign mostPopular_q1_out = mostPopular_q1_fu_50;

assign mostPopular_q2_1_fu_324_p3 = ((icmp_ln249_fu_318_p2[0:0] == 1'b1) ? zext_ln242_fu_269_p1 : mostPopular_q2_fu_54);

assign mostPopular_q2_out = mostPopular_q2_fu_54;

assign mostPopular_q3_4_fu_350_p3 = ((icmp_ln254_fu_344_p2[0:0] == 1'b1) ? zext_ln242_fu_269_p1 : mostPopular_q3_fu_58);

assign mostPopular_q3_out = mostPopular_q3_fu_58;

assign sext_ln239_fu_259_p1 = $signed(histogram_q0_q0);

assign sext_ln244_fu_288_p1 = $signed(histogram_q1_q0);

assign sext_ln249_fu_314_p1 = $signed(histogram_q2_q0);

assign sext_ln254_fu_340_p1 = $signed(histogram_q3_q0);

assign zext_ln236_fu_222_p1 = ap_sig_allocacmp_i_1;

assign zext_ln242_fu_269_p1 = i_1_reg_489;

endmodule //kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_236_6
