set SynModuleInfo {
  {SRCNAME isinf MODELNAME isinf RTLNAME kNN_PredictAll_isinf
    SUBMODULES {
      {MODELNAME kNN_PredictAll_fcmp_32ns_32ns_1_2_no_dsp_1 RTLNAME kNN_PredictAll_fcmp_32ns_32ns_1_2_no_dsp_1 BINDTYPE op TYPE fcmp IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_121_4 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_121_4 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_121_4
    SUBMODULES {
      {MODELNAME kNN_PredictAll_fsub_32ns_32ns_32_4_full_dsp_1 RTLNAME kNN_PredictAll_fsub_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fsub IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME kNN_PredictAll_fpext_32ns_64_2_no_dsp_1 RTLNAME kNN_PredictAll_fpext_32ns_64_2_no_dsp_1 BINDTYPE op TYPE fpext IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME kNN_PredictAll_dadd_64ns_64ns_64_5_full_dsp_1 RTLNAME kNN_PredictAll_dadd_64ns_64ns_64_5_full_dsp_1 BINDTYPE op TYPE dadd IMPL fulldsp LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME kNN_PredictAll_dmul_64ns_64ns_64_5_max_dsp_1 RTLNAME kNN_PredictAll_dmul_64ns_64ns_64_5_max_dsp_1 BINDTYPE op TYPE dmul IMPL maxdsp LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME kNN_PredictAll_flow_control_loop_pipe_sequential_init RTLNAME kNN_PredictAll_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME kNN_PredictAll_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_1 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_1 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_17_1
    SUBMODULES {
      {MODELNAME kNN_PredictAll_mux_205_64_1_1 RTLNAME kNN_PredictAll_mux_205_64_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_12 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_12 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_17_12}
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_13 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_13 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_17_13}
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_14 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_14 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_17_14}
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_15 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_15 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_17_15}
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_16 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_16 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_17_16}
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_17 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_17 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_17_17}
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_18 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_18 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_17_18}
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_19 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_19 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_17_19}
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_110 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_110 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_17_110}
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_111 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_111 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_17_111}
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_112 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_112 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_17_112}
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_113 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_113 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_17_113}
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_114 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_114 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_17_114}
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_115 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_115 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_17_115}
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_116 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_17_116 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_17_116}
  {SRCNAME kNN_Predict_4_Pipeline_18 MODELNAME kNN_Predict_4_Pipeline_18 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_18}
  {SRCNAME kNN_Predict_4_Pipeline_19 MODELNAME kNN_Predict_4_Pipeline_19 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_19}
  {SRCNAME kNN_Predict_4_Pipeline_20 MODELNAME kNN_Predict_4_Pipeline_20 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_20}
  {SRCNAME kNN_Predict_4_Pipeline_21 MODELNAME kNN_Predict_4_Pipeline_21 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_21}
  {SRCNAME kNN_Predict_4_Pipeline_VITIS_LOOP_236_6 MODELNAME kNN_Predict_4_Pipeline_VITIS_LOOP_236_6 RTLNAME kNN_PredictAll_kNN_Predict_4_Pipeline_VITIS_LOOP_236_6}
  {SRCNAME kNN_Predict_4 MODELNAME kNN_Predict_4 RTLNAME kNN_PredictAll_kNN_Predict_4
    SUBMODULES {
      {MODELNAME kNN_PredictAll_fdiv_32ns_32ns_32_9_no_dsp_1 RTLNAME kNN_PredictAll_fdiv_32ns_32ns_32_9_no_dsp_1 BINDTYPE op TYPE fdiv IMPL fabric LATENCY 8 ALLOW_PRAGMA 1}
      {MODELNAME kNN_PredictAll_fptrunc_64ns_32_2_no_dsp_1 RTLNAME kNN_PredictAll_fptrunc_64ns_32_2_no_dsp_1 BINDTYPE op TYPE fptrunc IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME kNN_PredictAll_mul_mul_11ns_6ns_17_4_1 RTLNAME kNN_PredictAll_mul_mul_11ns_6ns_17_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME kNN_PredictAll_mul_mul_11ns_6ns_16_4_1 RTLNAME kNN_PredictAll_mul_mul_11ns_6ns_16_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME kNN_PredictAll_dcmp_64ns_64ns_1_2_no_dsp_1 RTLNAME kNN_PredictAll_dcmp_64ns_64ns_1_2_no_dsp_1 BINDTYPE op TYPE dcmp IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME kNN_PredictAll_kNN_Predict_4_histogram_q0_RAM_AUTO_1R1W RTLNAME kNN_PredictAll_kNN_Predict_4_histogram_q0_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME kNN_PredictAll MODELNAME kNN_PredictAll RTLNAME kNN_PredictAll IS_TOP 1}
}
